# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='ip地址')),
                ('route', models.GenericIPAddressField(verbose_name='路由地址')),
                ('port', models.IntegerField(verbose_name='跳转端口')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostname', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='主机名')),
                ('group', models.IntegerField(choices=[(0, 'WebServer'), (1, 'DBServer')], default=0, verbose_name='群组')),
                ('cpu_core', models.IntegerField(verbose_name='CPU')),
                ('memory_total', models.IntegerField(verbose_name='内存')),
                ('nic_list', models.TextField(verbose_name='网络接口')),
                ('disk_list', models.TextField(verbose_name='磁盘')),
                ('ip', models.ManyToManyField(to='cmdb.Address', verbose_name='ip地址')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('format', models.CharField(choices=[('py2', '/usr/bin/python2.7'), ('py3', '/usr/bin/python3.6'), ('sh', '/bin/bash'), ('txt', '/usr/bin/cat')], default='txt', max_length=8, verbose_name='格式')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=128)),
                ('format', models.CharField(choices=[('py2', '/usr/bin/python2.7'), ('py3', '/usr/bin/python3.6'), ('sh', '/bin/bash'), ('txt', '/usr/bin/cat')], default='txt', max_length=8, verbose_name='格式')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
