# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_core',
            field=models.IntegerField(default=0, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk_list',
            field=models.TextField(default='', verbose_name='磁盘'),
        ),
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.CharField(choices=[('WebServer', 0), ('DBServer', 1)], default='WebServer', max_length=16, verbose_name='群组'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory_total',
            field=models.IntegerField(default=0, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='host',
            name='nic_list',
            field=models.TextField(default='', verbose_name='网络接口'),
        ),
    ]
