# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20181031_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
