# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('hostname', models.CharField(max_length=50)),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='host.Group')),
            ],
        ),
    ]
