# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20181025_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.Group'),
        ),
    ]
