# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=127)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Format')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=127)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Format')),
            ],
        ),
    ]
